apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "automaton.fullname" . }}-config
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "automaton.labels" . | nindent 4 }}
data:
  APP_PORT: "{{ .Values.app.service.port }}"
  LOG_LEVEL: "{{ .Values.config.logLevel }}"
  MAX_WORKERS: "{{ .Values.config.maxWorkers }}"
  GPU_ENABLED: "{{ .Values.config.gpuEnabled }}"

