apiVersion: v1
kind: Service
metadata:
  name: {{ include "automaton.fullname" . }}-app
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "automaton.labels" . | nindent 4 }}
    component: app
spec:
  type: {{ .Values.app.service.type }}
  ports:
  - port: {{ .Values.app.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.app.service.metricsPort }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "automaton.selectorLabels" . | nindent 4 }}
    component: app

